### ISSUE TITLE
boot/boot_tty.c:106:9: error: a label can only be part of a statement and a declaration is not a statement

### ISSUE THREAD

**Issue by VimIcewind** [arttnba3/ClosureOS#2]
gcc -pipe -ffreestanding -nostdlib -fno-pie -fno-stack-protector -mcmodel=large -c  boot/boot.S  boot/boot_tty.c boot/boot_main.c -I /root/GitHub/ClosureOS/code/include/ -I /root/GitHub/ClosureOS/code/arch/x86/include/
boot/boot_tty.c: In function ‘boot_putchar’:
boot/boot_tty.c:106:9: error: a label can only be part of a statement and a declaration is not a statement
  106 |         int left_ch_nr = max_ch_nr_x - cursor_x - 1;
      |         ^~~
boot/boot_tty.c:107:9: error: expected expression before ‘int’
  107 |         int space_nr = left_ch_nr > 4 ? 4 : left_ch_nr;
      |         ^~~
boot/boot_tty.c:108:29: error: ‘space_nr’ undeclared (first use in this function)
  108 |         for (int i = 0; i < space_nr; i++) {
      |                             ^~~~~~~~
boot/boot_tty.c:108:29: note: each undeclared identifier is reported only once for each function it appears in

**Comment by arttnba3** [comment]
Hi IceWind,

Thank you for your issue to report this. The reason for this error might be that your compiler doesn't support such features. Could you please tell me what's your compiler's version? The code can be compiled on my machine with `gcc 13.3.0`.

**Comment by arttnba3** [comment]
Hi IceWind,

Thank you for your issue to report this. However, the project has been rewritten, so some of the original code have been changed or discarded (include this one).

Anyway, thanks for your report and I'll consider to test the code under different environments before publish to make it more compatible.
